platform :android do
  desc "Upload a new Android version to the production Google Play Store"
  lane :production do
    upload_to_play_store(track: 'production', release_status: 'draft', aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}")
    #upload_to_play_store(track: 'production', release_status: 'completed', aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}")
  end

  desc "Upload a new Android internal version to Google Play"
  lane :internal do
    current_version = ENV['APP_VERSION'] || '1.0.0'
    major, minor, patch = current_version.split('.').map(&:to_i)
    patch += 1
    new_version = "#{major}.#{minor}.#{patch}"
    patch += 1
    new_code = "#{patch}"
    upload_to_play_store(track: 'internal', release_status: 'draft', aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}", version_name: new_version, version_code: new_code)
    #upload_to_play_store(track: 'internal', release_status: 'completed', aab: "#{ENV['ANDROID_BUILD_FILE_PATH']}")
  end
end
